version: '3.9'
services:
  postgres:
    image: postgres:15.2
    container_name: oou-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vbQRiqt53HYJrBfd0LPT
      POSTGRES_DB: oou
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
